name: arm-live-mate

on:
  push:
    branches:
      main
  workflow_dispatch:
  schedule:
    cron: 0 0 * * *

jobs:
  live-mate:
    
    strategy:
      fail-fast: false
      matrix:
        arch: [aarch64]
    
    name: live-mate-${{ matrix.arch}}
    runs-on: ${{ matrix.arch == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    timeout-minutes: 120
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Create environment file
        run: |
          cat > .env << EOF
          jenux_iso_arch=${{ matrix.arch }}
          jenux_iso_livemode=1
          jenux_iso_preset=mate
          EOF
          
      - name: Create output directory
        run: mkdir -p ./art
      
      - name: Build Docker image
        run: docker build -t jenux -f dockerfile $PWD
      
      - name: Run Docker container
        run: |
          docker run --privileged --env-file .env \
            -v $PWD/art:/build/jenux-build/out \
            -t jenux
      
      - name: Upload iso
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jenux-${{ matrix.arch }}.iso
          path: ./art/*.iso
          compression-level: 9
          if-no-files-found: error
          retention-days: 90
      
      - name: Upload vmdk
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jenux-${{ matrix.arch }}.vmdk
          path: ./art/*.vmdk
          compression-level: 9
          if-no-files-found: error
          retention-days: 90
