name: Build

on:
  push:
    branches:
      - main
      - docker
  pull_request:
    branches:
      - main
      - docker

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, i686, aarch64]
        livemode: [0, 1]
        preset: [base, basegui, gnome, mate, plasma]
    
    name: Build ${{ matrix.arch }}-${{ matrix.livemode == '1' && 'live' || 'installer' }}-${{ matrix.preset }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v5
      
      - name: Create environment file
        run: |
          cat > .env << EOF
          jenux_iso_arch=${{ matrix.arch }}
          jenux_iso_livemode=${{ matrix.livemode }}
          jenux_iso_preset=${{ matrix.preset }}
          EOF
          
      - name: Create output directory
        run: mkdir -p ./art
      
      - name: Build Docker image
        run: docker build -t jenux -f dockerfile $PWD
      
      - name: Run Docker container
        run: |
          docker run --privileged --env-file .env \
            -v $PWD/art:/build/jenux-build/out \
            -i jenux
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jenux-${{ matrix.arch }}-${{ matrix.livemode == '1' && 'live' || 'installer' }}-${{ matrix.preset }}
          path: ./art/*
          retention-days: 1